### PR TITLE
[NEW] Displays online and all users for each channel

### LINKED ISSUE #74: [FEATURE] A user info tab for each channel
A user info tab corresponding to each channel is needed. This would should the number of users online within the channel.

### PR DESCRIPTION
**Pull request by RonLek**
https://user-images.githubusercontent.com/28918901/110030922-4c918300-7d5c-11eb-8a9b-e46112e9bc50.mp4

Online and all users of a channel can now be viewed by signed in users.

Closes #74

### CODE REVIEW

**Review by dhruvjain99 — APPROVED** [review]

**Review by murtaza98 — APPROVED** [review]

**Comment by RonLek** [comment]
Closed in favor of #78

**Comment by dhruvjain99** [comment]
THIS PR IS YET TO BE REVIEWED. PLEASE DO NOT MERGE

**Comment by dhruvjain99** [comment]
@RonLek Could you please resolve the conflicts? I think you need to rebase this branch with the latest develop as the first commit in this PR has already been merged in PR #78

**Comment by RonLek** [comment]
Closed in favor of #90

**Pull request closed without merging**
