### PR TITLE
[FIX] Makes heights and widths cross browser compatible

### LINKED ISSUE #72: [BUG] Browser Incompatible Widths and Heights
Many browsers (like Mozilla Firefox) don't understand the `web-kit` widths which breaks the UI for different browser based users. For this we need to make the CSS widths cross-browser compatible.

Screenshot from 2021-03-02 00-56-17

Reference: https://stackoverflow.com/a/26276254/8316412

### PR DESCRIPTION
**Pull request by RonLek**
## Before

Screenshot from 2021-03-12 19-29-16

## Now

Screenshot from 2021-03-12 20-05-15

Fixes #72

### CODE REVIEW

**Comment by dhruvjain99** [comment]
@RonLek In firefox, the login page looks like the following, can you please increase the width of the login keeping it consistent with chrome.

image

**Comment by RonLek** [comment]
### Now

Screenshot from 2021-03-14 00-04-43

**Comment by dhruvjain99** [comment]
@murtaza98 @Sing-Li we can merge this PR.

**Review by dhruvjain99 — APPROVED** [review]

**Review by Sing-Li — APPROVED** [review]

**Comment by Sing-Li** [comment]
@RonLek pls fix merge conflicts.  thx

**Comment by RonLek** [comment]
Done @Sing-Li . We can merge this in.

**Pull request merged**
